// Daha zengin palet (22 renk)
export const COLORS = [
  { name: 'Kırmızı',        value: '#ef4444' },
  { name: 'Bordo',          value: '#991b1b' },
  { name: 'Mercan',         value: '#fb7185' },
  { name: 'Pembe',          value: '#ec4899' },
  { name: 'Magenta',        value: '#d946ef' },
  { name: 'Mor',            value: '#8b5cf6' },
  { name: 'Eflatun',        value: '#a78bfa' },
  { name: 'Lacivert',       value: '#1e3a8a' },
  { name: 'Mavi',           value: '#3b82f6' },
  { name: 'Gökyüzü',        value: '#38bdf8' },
  { name: 'Turkuaz',        value: '#14b8a6' },
  { name: 'Cam Göbeği',     value: '#06b6d4' },
  { name: 'Yeşil',          value: '#10b981' },
  { name: 'Zümrüt',         value: '#059669' },
  { name: 'Nane',           value: '#34d399' },
  { name: 'Sarı',           value: '#eab308' },
  { name: 'Kehribar',       value: '#f59e0b' },
  { name: 'Turuncu',        value: '#f97316' },
  { name: 'Yanık Turuncu',  value: '#c2410c' },
  { name: 'Kahverengi',     value: '#92400e' },
  { name: 'Gri',            value: '#6b7280' },
  { name: 'Antrasit',       value: '#374151' },
  { name: 'Somon',         value: '#FCA5A5' },
{ name: 'Limon Yeşili',  value: '#84CC16' },
{ name: 'Çivit',         value: '#6366F1' },
{ name: 'Zeytin',        value: '#6B8E23' },
{ name: 'Altın',         value: '#D4AF37' },
{ name: 'Bakır',         value: '#B87333' },
{ name: 'Lavanta',     value: '#C084FC' },
{ name: 'Gece Mavisi', value: '#0B3D91' },
];
