// backend/src/colors.js
export const COLORS = [
  { name: 'Kırmızı',        value: '#ef4444' },
  { name: 'Bordo',          value: '#7f1d1d' },
  { name: 'Mercan',         value: '#fb7185' },
  { name: 'Pembe',          value: '#ec4899' },
  { name: 'Magenta',        value: '#d946ef' },
  { name: 'Mor',            value: '#a855f7' },
  { name: 'Eflatun',        value: '#c084fc' },
  { name: 'Lacivert',       value: '#1e3a8a' },
  { name: 'Mavi',           value: '#3b82f6' },
  { name: 'Gökyüzü',        value: '#38bdf8' },
  { name: 'Turkuaz',        value: '#14b8a6' },
  { name: 'Cam Göbeği',     value: '#06b6d4' },
  { name: 'Yeşil',          value: '#22c55e' },
  { name: 'Zümrüt',         value: '#059669' },
  { name: 'Nane',           value: '#34d399' },
  { name: 'Sarı',           value: '#f59e0b' },
  { name: 'Kehribar',       value: '#d97706' },
  { name: 'Turuncu',        value: '#f97316' },
  { name: 'Yanık Turuncu',  value: '#ea580c' },
  { name: 'Kahverengi',     value: '#92400e' },
  { name: 'Gri',            value: '#9ca3af' },
  { name: 'Antrasit',       value: '#475569' },
  { name: 'Somon',          value: '#fda4af' },
  { name: 'Limon Yeşili',   value: '#84cc16' },
  { name: 'Çivit',          value: '#4f46e5' },
  { name: 'Zeytin',         value: '#6b8e23' },
  { name: 'Altın',          value: '#eab308' },
  { name: 'Bakır',          value: '#b45309' },
  { name: 'Lavanta',        value: '#a78bfa' },
  { name: 'Gece Mavisi',    value: '#0f172a' },
];
